### ISSUE TITLE
Error: The word vector model is being loaded.

### ISSUE THREAD

**Issue by arossbach10** [anastasia-zhukova/ANEA#1]
Hi,

I wanted to try the model but an error occurred:

The word vector model is being loaded.
Traceback (most recent call last):
  File "run_anea.py", line 141, in <module>
    run()
  File "run_anea.py", line 124, in run
    graph = Graph(noun_terms, topN_terms=topN)
  File "/content/ANEA/category_identificator/ANEA_annotator/graph/graph.py", line 35, in __init__
    self._domain_types_identif()
  File "/content/ANEA/category_identificator/ANEA_annotator/graph/graph.py", line 247, in _domain_types_identif
    self.model = get_model()
  File "/content/ANEA/utils/wordvectors.py", line 39, in get_model
    model = WordEmbeddings()
  File "/content/ANEA/utils/wordvectors.py", line 17, in __init__
    self._model = load_facebook_model(wordvectors[we_name])
  File "/usr/local/lib/python3.7/dist-packages/gensim/models/fasttext.py", line 1142, in load_facebook_model
    return _load_fasttext_format(path, encoding=encoding, full_model=True)
  File "/usr/local/lib/python3.7/dist-packages/gensim/models/fasttext.py", line 1222, in _load_fasttext_format
    m = gensim.models._fasttext_bin.load(fin, encoding=encoding, full_model=full_model)
  File "/usr/local/lib/python3.7/dist-packages/gensim/models/_fasttext_bin.py", line 341, in load
    raw_vocab, vocab_size, nwords, ntokens = _load_vocab(fin, new_format, encoding=encoding)
  File "/usr/local/lib/python3.7/dist-packages/gensim/models/_fasttext_bin.py", line 194, in _load_vocab
    raise NotImplementedError("Supervised fastText models are not supported")
NotImplementedError: Supervised fastText models are not supported

**Comment by anastasia-zhukova** [comment]
Hi @arossbach10 , 

Could you send me which python version you are running and gensim version? 

Thanks
